name: Haxelib

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/upload-artifact@v3
        with:
          name: openfl-utest-tools-haxelib
          path: |
            src/
            templates/
            haxelib.json
            README.md
            LICENSE
            CHANGELOG.md
          if-no-files-found: error
