name: Samples

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  samples-neko:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.5
    - name: Set up Haxelib dependencies
      run: |
        haxelib install lime --quiet
        haxelib install openfl --quiet
        haxelib install utest --quiet
        haxelib install hxargs --quiet
        haxelib dev openfl-utest-tools $GITHUB_WORKSPACE
    - name: "Run Tests: samples/basic"
      working-directory: samples/basic
      run: haxelib run openfl-utest-tools test neko
    - name: "Run Tests: samples/custom-tests-source-path"
      working-directory: samples/custom-tests-source-path
      run: haxelib run openfl-utest-tools test neko --source tests/src